### ISSUE TITLE
no method named `data` found for struct `DataUrl` in the current scope

### ISSUE THREAD

**Issue by davehorner** [Y2Z/dataurl#10]
I've been trying to get a dataurl from a canvas to decode.  I'm trying:
```
   let mut d: &[u8] = data.as_bytes();
    if data.starts_with("data:image/jpeg;base64,") {
        use dataurl::DataUrl;
let data_url = DataUrl::parse(data).unwrap();
d=data_url.data();
    }
```

I see that     pub fn data(&self) -> &[u8] {
https://github.com/Y2Z/dataurl/blob/5e06144373dbcb9aaf6cd602b9978603636bfd1f/src/lib.rs#L255

But I am unable to access it via my main.rs
```
error[E0599]: no method named `data` found for struct `DataUrl` in the current scope
   --> src\main.rs:354:12
    |
354 | d=data_url.data();
    |            ^^^^
    |            |
    |            private field, not a method
    |            help: there is a method with a similar name: `get_data`
```
any ideas?

**Comment by snshn** [comment]
It's a very strange bug, since https://github.com/Y2Z/dataurl/blob/master/tests/lib/parse.rs#L16 shows that `.data()` is accessible.  I'm currently not able to reproduce it.

**Comment by davehorner** [comment]
Yes, strange indeed.  It's been awhile; I'm closing as I don't know if I can reproduce it or not either now.
